version: '3.3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    networks:
      - mybridge
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./datasets:/datasets

  cassandra-web:
    image: ipushc/cassandra-web
    container_name: cassandra-web-container
    ports:
      - "3000:80"  # Mapeia a porta 3000 do host para a porta 80 do container
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      - HOST_PORT=:80
      - READ_ONLY=false
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra  
      - CASSANDRA_PASSWORD=cassandra  
    command: ["/wait-for-it.sh", "cassandra:9042", "--", "./service", "-c", "config.yaml"]  # Um arquivo config.yaml deve estar com disponível e com a sintaxe correta para fornecer as diretivas adicionais de customização. 
    depends_on:
      - cassandra
    networks:
      - mybridge

networks:
  mybridge:
#    driver: bridge
    external: true

#volumes:
#  cassandra_data:
#  datasets:
